### PR TITLE
Some devpanel fixes

### LINKED ISSUE #114: flow-graph connectors are not draw outside viewport
``` js
var canRead = new Value({value: true});
var canWrite = new Value({value: true});
var hasAccess = new Expression(
  canRead,
  canWrite,
  (canRead, canWrite) => canRead && canWrite
);

var needToPay = new Value({value: 100});
var totalMoney = new Value({value: 100});
var canPay = new Expression(
  totalMoney,
  needToPay,
  (needToPay, totalMoney) => totalMoney >= needToPay
);

var maxApply = new Value({value: 10});
var currentApply = new Value({value: 9});
var canApply = new Expression(
  currentApply,
  maxApply,
  (currentApply, maxApply) => currentApply <= maxApply
);

var buttonDisabled = new Expression(
  hasAccess,
  canApply,
  canPay,
  (hasAccess, canApply, canPay) => !hasAccess || !canApply || !canPay
);

...
  new Button({
    caption: 'Apply',
    binding: {
      disabled: buttonDisabled
    }
  })
...
```

I've got this in data-flow inspector:

### PR DESCRIPTION
**Pull request by smelukov**
- **fix**: old `openFile` calls
- **fix**: cancel inspect mode after l10n inspector
- **fix**: reset source panel visibility when close the inspector
- **fix**: now it works on IE!
- **fix**: correct width on flow chart (fixes #114)
- **feat**: inspect mode can be canceled by ESC-key

### CODE REVIEW

File: src/basis/utils/json-parser.js [hunk 1]
```diff
@@ -223,15 +223,15 @@ var JsonParser = (function () {
             value: function _testKeyword() {
                 var _this = this;
 
-                var matched = Object.keys(keywordsTokens).find(function (name) {
+                var matched = Object.keys(keywordsTokens).filter(function (name) {
```
Comment (lahmatiy) [inline src/basis/utils/json-parser.js]: it's better to contribute back to https://github.com/vtrushin/json-to-ast
and `for..in` with no substr on every keywordsTokens key is better

File: src/devpanel/panel/index.js [hunk 2]
```diff
@@ -18,6 +18,12 @@ var inspectMode = require('api').inspect;
 var inspector = require('../inspector/index.js');
 var currentInspectorName = inspector.currentName;
 
+var KEY_ESC = 27;
+
+inspectBasisDomEvent.captureEvent('keydown', function(event){
```
Comment (lahmatiy) [inline src/devpanel/panel/index.js]: show add global handler on inspect mode on and remove on off
`captureEvent` is a bad choice since the can be a editor in future

Comment (smelukov) [inline src/devpanel/panel/index.js]: fixed

File: src/devpanel/panel/index.js [hunk 3]
```diff
@@ -18,6 +18,18 @@ var inspectMode = require('api').inspect;
 var inspector = require('../inspector/index.js');
 var currentInspectorName = inspector.currentName;
 
+var KEY_ESC = 27;
+var keydownHandler = function(event){
```
Comment (lahmatiy) [inline src/devpanel/panel/index.js]: `keydownHandler` -> `cancelInspectModeOnEsc`

File: src/devpanel/sync-devtools.js [hunk 4]
```diff
@@ -38,9 +38,17 @@ function emitEvent(channelId, data){
   if (DEBUG)
     console.log('[basisjs.devpanel] emit event', channelId, data);
 
-  document.dispatchEvent(new CustomEvent(channelId, {
-    detail: data
-  }));
+  // IE does not support CustomEvent constructor
+  if (typeof document.createEvent == 'function'){
+    var evt = document.createEvent('CustomEvent');
```
Comment (lahmatiy) [inline src/devpanel/sync-devtools.js]: why not `event`?

Comment (smelukov) [inline src/devpanel/sync-devtools.js]: fixed

File: src/devpanel/panel/index.js (hunk 3 above)
Comment (smelukov) [inline src/devpanel/panel/index.js]: fixed
